# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: APACHE-2.0

- name: Deploy Helm chart
  run_once: true
  kubernetes.core.helm:
    name: "{{ valkey_helm_release_name }}"
    chart_ref: "{{ valkey_helm_chart_ref }}"
    release_namespace: "{{ valkey_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
    values: "{{ _valkey_helm_values | combine(valkey_helm_values, recursive=True) }}"
