# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only
# Atmosphere-Rebuild-Time: 2025-01-04T23:34:28Z

contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://packages.atmosphere.dev/oss/signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
    - https://packages.atmosphere.dev/oss/2024.2

archs:
 - amd64
 - arm64
