# Copyright (c) 2024 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - atmosphere-chart-vendor
        - atmosphere-golang-go-test
        - atmosphere-linters
        - atmosphere-tox-promtool-test
        - atmosphere-tox-helm-unittest
        - atmosphere-tox-py3
        - atmosphere-build-collection:
            dependencies: &build_apko_image_jobs
              - name: atmosphere-build-apko-image-barbican
                soft: true
              # - name: atmosphere-build-apko-image-cinder
              #   soft: true
              - name: atmosphere-build-apko-image-designate
                soft: true
              # - name: atmosphere-build-apko-image-glance
              #   soft: true
              - name: atmosphere-build-apko-image-heat
                soft: true
              # - name: atmosphere-build-apko-image-horizon
              #   soft: true
              # - name: atmosphere-build-apko-image-ironic
              #   soft: true
              # - name: atmosphere-build-apko-image-keepalived
              #   soft: true
              # - name: atmosphere-build-apko-image-keystone
              #   soft: true
              - name: atmosphere-build-apko-image-kubernetes-entrypoint
                soft: true
              # - name: atmosphere-build-apko-image-libvirtd
              #   soft: true
              # - name: atmosphere-build-apko-image-magnum
              #   soft: true
              # - name: atmosphere-build-apko-image-manila
              #   soft: true
              # - name: atmosphere-build-apko-image-netoffload
              #   soft: true
              # - name: atmosphere-build-apko-image-neutron
              #   soft: true
              # - name: atmosphere-build-apko-image-nova
              #   soft: true
              # - name: atmosphere-build-apko-image-nova-ssh
              #   soft: true
              - name: atmosphere-build-apko-image-octavia
                soft: true
              # - name: atmosphere-build-apko-image-openvswitch
              #   soft: true
              # - name: atmosphere-build-apko-image-ovn
              #   soft: true
              # - name: atmosphere-build-apko-image-placement
              #   soft: true
              - name: atmosphere-build-apko-image-python-openstackclient
                soft: true
              # - name: atmosphere-build-apko-image-staffeln
              #   soft: true
              # - name: atmosphere-build-apko-image-tempest
              #   soft: true
        - atmosphere-molecule-aio-keycloak:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-aio-openvswitch:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-aio-ovn:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-csi-local-path-provisioner:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-csi-rbd:
            dependencies: *build_apko_image_jobs
    gate:
      jobs:
        - atmosphere-chart-vendor
        - atmosphere-golang-go-test
        - atmosphere-linters
        - atmosphere-tox-py3
        - atmosphere-build-collection:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-aio-keycloak:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-aio-openvswitch:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-aio-ovn:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-csi-local-path-provisioner:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-csi-rbd:
            dependencies: *build_apko_image_jobs
    release:
      jobs:
        - atmosphere-publish-collection
    periodic:
      jobs:
        - atmosphere-molecule-aio-upgrade-openvswitch:
            dependencies: *build_apko_image_jobs
        - atmosphere-molecule-aio-upgrade-ovn:
            dependencies: *build_apko_image_jobs
