# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: APACHE-2.0

_valkey_helm_values:
  replica:
    replicaCount: 3
  auth:
    enabled: false
  image:
    registry: "{{ atmosphere_images['valkey'] | vexxhost.kubernetes.docker_image('domain') }}"
    repository: "{{ atmosphere_images['valkey'] | vexxhost.kubernetes.docker_image('path') }}"
    tag: "{{ atmosphere_images['valkey'] | vexxhost.kubernetes.docker_image('tag') }}"
